version: "3.0"
services: 
  app:
    build: app/
    volumes: 
      - ./app:/usr/src/app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - 80:3000
  db:
    image: 'mongo'
    volumes: 
      - dbdata:/data/db
    ports: 
      - 27017:27017

volumes: 
  dbdata:
    